try old sync script

diff --git a/.github/workflows/sync.yml b/.github/workflows/sync.yml
--- a/.github/workflows/sync.yml
+++ b/.github/workflows/sync.yml
@@ -20,7 +20,21 @@ jobs:
       - name: Check for unpushed commits
         id: check_unpushed
         run: |
-          git diff --exit-code || echo "HAS_COMMITS=true" >> $GITHUB_OUTPUT
+          git fetch origin
+          echo 'a'
+          git log origin/main..upstream/main
+          echo 'b'
+          git log upstream/main..origin/main
+          git diff --exit-code || echo "via diff HAS_COMMITS=true"
+          UNPUSHED=$(git log origin/main..upstream/main)
+          echo "UNPUSHED=$UNPUSHED"
+          if [ -z "$UNPUSHED" ]; then
+            echo "no new commits - aborting pr creation"
+            echo "HAS_COMMITS=false" >> $GITHUB_OUTPUT
+          else
+            echo "new commits found - creating pr"
+            echo "HAS_COMMITS=true" >> $GITHUB_OUTPUT
+          fi
       - name: Create Pull Request
         if: ${{ steps.check_unpushed.outputs.HAS_COMMITS == 'true' }}
         uses: peter-evans/create-pull-request@v6
